name: Formatting

on:
  pull_request:
    paths:
      - "src/**.hs"
      - scrive-prelude.cabal
      - .github/workflows/build.yaml
  push:
    branches:
      - main

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fourmolu/fourmolu-action@v5
        with:
          pattern: |
            src/**/*.hs
            test/**/*.hs
            app/**/*.hs
